In [3]:
import pandas as pd

In [4]:
merged = pd.read_csv('../2_DataCleaning/cleaned_data/clean_merged_data.csv')
merged.head(200)

,Unnamed: 0,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,0,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,0
1,1,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,ACT,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,1
2,2,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,2
3,3,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,3
4,4,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,a.j. brown,00-0035676,NaN,2021.0,2022,PHI,WR,ACT,73.0,...,3.0,Other,NaN,NaN,Not injury related - personal matter,NaN,NaN,Full Participation in Practice,0.0,26
196,196,a.j. brown,00-0035676,2020.0,NaN,2022,PHI,WR,ACT,73.0,...,3.0,Other,NaN,NaN,Not injury related - personal matter,NaN,NaN,Full Participation in Practice,0.0,27
197,197,a.j. brown,00-0035676,2020.0,NaN,2022,PHI,WR,ACT,73.0,...,3.0,Other,NaN,NaN,Not injury related - personal matter,NaN,NaN,Full Participation in Practice,0.0,27
198,198,a.j. brown,00-0035676,2020.0,NaN,2022,PHI,WR,ACT,73.0,...,3.0,Other,NaN,NaN,Not injury related - personal matter,NaN,NaN,Full Participation in Practice,0.0,27
199,199,a.j. brown,00-0035676,NaN,2021.0,2022,PHI,WR,ACT,73.0,...,3.0,Other,NaN,NaN,Not injury related - personal matter,NaN,NaN,Full Participation in Practice,0.0,27

In [5]:
counts = pd.read_csv('../2_DataCleaning/cleaned_data/injury_counts.csv')
counts.head()

,full_name,Abdomen,Achilles,Ankle,Appendicitis,Appendix,Back,Biceps,Calf,Chest,...,right Elbow,right Finger,right Groin,right Hamstring,right Hip,right Knee,right Quadricep,right Shoulder,right Thumb,"toe, pec, knee, hip"
0,a'shawn robinson,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,a.j. cann,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,a.j. epenesa,0,0,38,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,a.j. green,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,a.j. parker,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
counts = counts.head(3)

In [7]:
counts

,full_name,Abdomen,Achilles,Ankle,Appendicitis,Appendix,Back,Biceps,Calf,Chest,...,right Elbow,right Finger,right Groin,right Hamstring,right Hip,right Knee,right Quadricep,right Shoulder,right Thumb,"toe, pec, knee, hip"
0,a'shawn robinson,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,a.j. cann,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,a.j. epenesa,0,0,38,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
merged.shape

(308923, 23)

In [9]:
merged = merged.head(100)

In [10]:
merged.shape

(100, 23)

In [11]:
#merged.to_csv('../data/test_merged.csv')

In [12]:
test = pd.read_csv('../data/test_merged.csv')
test.shape

FileNotFoundError: [Errno 2] No such file or directory: '../data/test_merged.csv'

In [13]:
test.head()

NameError: name 'test' is not defined

In [27]:
test = test.drop(columns = ['Unnamed: 0', 'Unnamed: 0.1'])
test.head()

,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,0
1,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,ACT,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,1
2,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,2
3,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,3
4,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,4

In [28]:
test = test.groupby('full_name', as_index=False).last()

test = test.sort_values('full_name')

test.head()

,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,33
1,a.j. brown,00-0035676,2020.0,2021.0,2022,PHI,WR,ACT,73.0,226.0,...,3.0,Other,None,NaN,Not injury related - resting player,NaN,None,Full Participation in Practice,0.0,10

### Group By Name

In [14]:
merge_name = pd.read_csv('../2_DataCleaning/cleaned_data/clean_merged_data.csv')
merge_name.head()

,Unnamed: 0,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,0,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,0
1,1,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,ACT,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,1
2,2,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,2
3,3,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,3
4,4,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,4

In [15]:
merge_name = merge_name.drop(columns = ['Unnamed: 0'])

merge_name = merge_name.groupby('full_name', as_index=False).last()

merge_name = merge_name.sort_values('full_name')

merge_name.head()

,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Lower Body,Knee,None,Knee,None,Out,Did Not Participate In Practice,0.0,33
1,a.j. brown,00-0035676,2020.0,2021.0,2022,PHI,WR,ACT,73.0,226.0,...,3.0,Other,None,None,Not injury related - resting player,None,None,Limited Participation in Practice,0.0,359
2,a.j. cann,00-0032255,2020.0,NaN,2022,HOU,G,ACT,75.0,325.0,...,7.0,Other,Illness,None,Illness,None,Questionable,Full Participation in Practice,0.0,33
3,a.j. cole,00-0035190,NaN,NaN,2022,LV,P,ACT,76.0,220.0,...,3.0,Other,None,None,Illness,None,None,Full Participation in Practice,0.0,16
4,a.j. dillon,00-0036265,NaN,NaN,2022,GB,RB,ACT,72.0,250.0,...,2.0,Other,None,None,Concussion Protocol,None,None,Full Participation in Practice,0.0,50

In [16]:
merge_name.shape

(1413, 22)

## Group by ID

In [17]:
merge = pd.read_csv('../2_DataCleaning/cleaned_data/clean_merged_data.csv')
merge.head()

,Unnamed: 0,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,0,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,0
1,1,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,ACT,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,1
2,2,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,2
3,3,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,3
4,4,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,4

In [18]:
merge = merge.drop(columns = ['Unnamed: 0'])

merge_id = merge.groupby('gsis_id', as_index=False).last()

merge_id = merge_id.sort_values('gsis_id')

merge_id.head()

,gsis_id,full_name,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,00-0019596,tom brady,NaN,NaN,2022,TB,QB,ACT,76.0,225.0,...,22.0,Other,None,None,Not injury related - resting player,right Finger,None,Full Participation in Practice,0.0,215
1,00-0022531,jason peters,2020.0,2021.0,2022,DAL,T,DEV,76.0,328.0,...,18.0,Other,Hip,None,Hip,None,Out,Did Not Participate In Practice,0.0,75
2,00-0022824,andy lee,NaN,NaN,2022,ARI,P,ACT,73.0,185.0,...,18.0,Other,Illness,None,None,None,Questionable,\n,0.0,16
3,00-0023252,robbie gould,NaN,NaN,2022,SF,K,ACT,72.0,190.0,...,17.0,Other,None,None,left Knee,None,None,Full Participation in Practice,0.0,19
4,00-0023459,aaron rodgers,NaN,NaN,2022,GB,QB,ACT,74.0,225.0,...,17.0,Other,None,None,right Thumb,Knee,None,Full Participation in Practice,0.0,203

In [19]:
merge_id.shape

(1418, 22)

In [26]:
merge_id['count_out'] = merge.groupby('gsis_id')['report_status_x'].transform('size')

merge.loc[df['report_status_x'] == 'Out', 'count_out'] = 1

#df = df.sort_values('gsis_id')  

merge_id['count_out']

TypeError: unhashable type: 'Series'

In [27]:
merge_id

,gsis_id,full_name,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count,count_out
0,00-0019596,tom brady,NaN,NaN,2022,TB,QB,ACT,76.0,225.0,...,Other,None,None,Not injury related - resting player,right Finger,None,Full Participation in Practice,0.0,215,34
1,00-0022531,jason peters,2020.0,2021.0,2022,DAL,T,DEV,76.0,328.0,...,Other,Hip,None,Hip,None,Out,Did Not Participate In Practice,0.0,75,34
2,00-0022824,andy lee,NaN,NaN,2022,ARI,P,ACT,73.0,185.0,...,Other,Illness,None,None,None,Questionable,\n,0.0,16,34
3,00-0023252,robbie gould,NaN,NaN,2022,SF,K,ACT,72.0,190.0,...,Other,None,None,left Knee,None,None,Full Participation in Practice,0.0,19,34
4,00-0023459,aaron rodgers,NaN,NaN,2022,GB,QB,ACT,74.0,225.0,...,Other,None,None,right Thumb,Knee,None,Full Participation in Practice,0.0,203,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1413,00-0038130,andrew booth,NaN,NaN,2022,MIN,CB,RES,72.0,200.0,...,Lower Body,Knee,None,Knee,None,Out,Did Not Participate In Practice,0.0,89,2160
1414,00-0038133,boye mafe,NaN,NaN,2022,SEA,LB,ACT,76.0,265.0,...,Other,None,None,Shoulder,None,None,Full Participation in Practice,0.0,17,2160
1415,00-0038134,kenneth walker,NaN,NaN,2022,SEA,RB,ACT,69.0,210.0,...,Other,Ankle,Back,Ankle,Illness,Questionable,Limited Participation in Practice,0.0,215,2160
1416,00-0038135,jaquan brisker,NaN,NaN,2022,CHI,S,ACT,73.0,202.0,...,Other,Concussion,None,Not injury related - personal matter,None,Out,Full Participation in Practice,0.0,67,2160
1417,00-0038142,david ojabo,NaN,NaN,2022,BAL,LB,RES,76.0,250.0,...,Other,None,None,Achilles,None,None,Full Participation in Practice,0.0,17,2160

### With 'Out' count

In [28]:
df = pd.read_csv('../2_DataCleaning/cleaned_data/clean_merged_data.csv')  

df = df.drop(columns=['Unnamed: 0'])

In [29]:
df = df.groupby('gsis_id', as_index=False).last()  

df['count_out'] = df.groupby('gsis_id')['report_status_x'].transform('size')

In [30]:
df

,gsis_id,full_name,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count,count_out
0,00-0019596,tom brady,NaN,NaN,2022,TB,QB,ACT,76.0,225.0,...,Other,None,None,Not injury related - resting player,right Finger,None,Full Participation in Practice,0.0,215,1
1,00-0022531,jason peters,2020.0,2021.0,2022,DAL,T,DEV,76.0,328.0,...,Other,Hip,None,Hip,None,Out,Did Not Participate In Practice,0.0,75,1
2,00-0022824,andy lee,NaN,NaN,2022,ARI,P,ACT,73.0,185.0,...,Other,Illness,None,None,None,Questionable,\n,0.0,16,1
3,00-0023252,robbie gould,NaN,NaN,2022,SF,K,ACT,72.0,190.0,...,Other,None,None,left Knee,None,None,Full Participation in Practice,0.0,19,1
4,00-0023459,aaron rodgers,NaN,NaN,2022,GB,QB,ACT,74.0,225.0,...,Other,None,None,right Thumb,Knee,None,Full Participation in Practice,0.0,203,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1413,00-0038130,andrew booth,NaN,NaN,2022,MIN,CB,RES,72.0,200.0,...,Lower Body,Knee,None,Knee,None,Out,Did Not Participate In Practice,0.0,89,1
1414,00-0038133,boye mafe,NaN,NaN,2022,SEA,LB,ACT,76.0,265.0,...,Other,None,None,Shoulder,None,None,Full Participation in Practice,0.0,17,1
1415,00-0038134,kenneth walker,NaN,NaN,2022,SEA,RB,ACT,69.0,210.0,...,Other,Ankle,Back,Ankle,Illness,Questionable,Limited Participation in Practice,0.0,215,1
1416,00-0038135,jaquan brisker,NaN,NaN,2022,CHI,S,ACT,73.0,202.0,...,Other,Concussion,None,Not injury related - personal matter,None,Out,Full Participation in Practice,0.0,67,1
1417,00-0038142,david ojabo,NaN,NaN,2022,BAL,LB,RES,76.0,250.0,...,Other,None,None,Achilles,None,None,Full Participation in Practice,0.0,17,1

In [31]:
df.loc[df['report_status_x'] == 'Out', 'count_out'] = 1

df = df.sort_values('gsis_id')  

df

,gsis_id,full_name,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count,count_out
0,00-0019596,tom brady,NaN,NaN,2022,TB,QB,ACT,76.0,225.0,...,Other,None,None,Not injury related - resting player,right Finger,None,Full Participation in Practice,0.0,215,1
1,00-0022531,jason peters,2020.0,2021.0,2022,DAL,T,DEV,76.0,328.0,...,Other,Hip,None,Hip,None,Out,Did Not Participate In Practice,0.0,75,1
2,00-0022824,andy lee,NaN,NaN,2022,ARI,P,ACT,73.0,185.0,...,Other,Illness,None,None,None,Questionable,\n,0.0,16,1
3,00-0023252,robbie gould,NaN,NaN,2022,SF,K,ACT,72.0,190.0,...,Other,None,None,left Knee,None,None,Full Participation in Practice,0.0,19,1
4,00-0023459,aaron rodgers,NaN,NaN,2022,GB,QB,ACT,74.0,225.0,...,Other,None,None,right Thumb,Knee,None,Full Participation in Practice,0.0,203,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1413,00-0038130,andrew booth,NaN,NaN,2022,MIN,CB,RES,72.0,200.0,...,Lower Body,Knee,None,Knee,None,Out,Did Not Participate In Practice,0.0,89,1
1414,00-0038133,boye mafe,NaN,NaN,2022,SEA,LB,ACT,76.0,265.0,...,Other,None,None,Shoulder,None,None,Full Participation in Practice,0.0,17,1
1415,00-0038134,kenneth walker,NaN,NaN,2022,SEA,RB,ACT,69.0,210.0,...,Other,Ankle,Back,Ankle,Illness,Questionable,Limited Participation in Practice,0.0,215,1
1416,00-0038135,jaquan brisker,NaN,NaN,2022,CHI,S,ACT,73.0,202.0,...,Other,Concussion,None,Not injury related - personal matter,None,Out,Full Participation in Practice,0.0,67,1
1417,00-0038142,david ojabo,NaN,NaN,2022,BAL,LB,RES,76.0,250.0,...,Other,None,None,Achilles,None,None,Full Participation in Practice,0.0,17,1

### Transforming multiple columns

In [32]:
import pandas as pd

# Read in the CSV 
df = pd.read_csv('../2_DataCleaning/cleaned_data/clean_merged_data.csv')

# Drop unnecessary columns
df = df.drop(columns=['Unnamed: 0'])

# Groupby player ID
df = df.groupby('gsis_id', as_index=False).last()

# Get count of each report status per group
status_counts = df.groupby('gsis_id')['report_status_x'].value_counts().unstack()

# Rename columns 
status_counts.columns = [f'num_{col}' for col in status_counts.columns]

# Join the count columns back to the df
df = df.join(status_counts)

df

,gsis_id,full_name,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count,num_Doubtful,num_Out,num_Questionable
0,00-0019596,tom brady,NaN,NaN,2022,TB,QB,ACT,76.0,225.0,...,None,Not injury related - resting player,right Finger,None,Full Participation in Practice,0.0,215,NaN,NaN,NaN
1,00-0022531,jason peters,2020.0,2021.0,2022,DAL,T,DEV,76.0,328.0,...,None,Hip,None,Out,Did Not Participate In Practice,0.0,75,NaN,NaN,NaN
2,00-0022824,andy lee,NaN,NaN,2022,ARI,P,ACT,73.0,185.0,...,None,None,None,Questionable,\n,0.0,16,NaN,NaN,NaN
3,00-0023252,robbie gould,NaN,NaN,2022,SF,K,ACT,72.0,190.0,...,None,left Knee,None,None,Full Participation in Practice,0.0,19,NaN,NaN,NaN
4,00-0023459,aaron rodgers,NaN,NaN,2022,GB,QB,ACT,74.0,225.0,...,None,right Thumb,Knee,None,Full Participation in Practice,0.0,203,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1413,00-0038130,andrew booth,NaN,NaN,2022,MIN,CB,RES,72.0,200.0,...,None,Knee,None,Out,Did Not Participate In Practice,0.0,89,NaN,NaN,NaN
1414,00-0038133,boye mafe,NaN,NaN,2022,SEA,LB,ACT,76.0,265.0,...,None,Shoulder,None,None,Full Participation in Practice,0.0,17,NaN,NaN,NaN
1415,00-0038134,kenneth walker,NaN,NaN,2022,SEA,RB,ACT,69.0,210.0,...,Back,Ankle,Illness,Questionable,Limited Participation in Practice,0.0,215,NaN,NaN,NaN
1416,00-0038135,jaquan brisker,NaN,NaN,2022,CHI,S,ACT,73.0,202.0,...,None,Not injury related - personal matter,None,Out,Full Participation in Practice,0.0,67,NaN,NaN,NaN
1417,00-0038142,david ojabo,NaN,NaN,2022,BAL,LB,RES,76.0,250.0,...,None,Achilles,None,None,Full Participation in Practice,0.0,17,NaN,NaN,NaN

In [33]:
df['num_Out'].value_counts()

Series([], Name: num_Out, dtype: int64)

## Just trying to get 'Out' counts

In [34]:
df = pd.read_csv('../2_DataCleaning/cleaned_data/clean_merged_data.csv')

In [35]:
print(df.shape)
df.head()

(308923, 23)

,Unnamed: 0,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,0,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,0
1,1,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,ACT,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,1
2,2,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,2
3,3,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,3
4,4,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,4

In [36]:
## Drop rows with illness as primary injury
print(df[df['report_primary_injury_x'] != 'Illness'].shape)
df = df[df['report_primary_injury_x'] != 'Illness']

(300726, 23)

In [37]:
df[df['report_status_x'] == 'Out'].head()

,Unnamed: 0,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
17,17,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,6.0,17
18,18,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,ACT,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,18
19,19,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,19
20,20,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,20
21,21,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,21

In [38]:
df.dtypes

Unnamed: 0                     int64
full_name                     object
gsis_id                       object
season_20                    float64
season_21                    float64
season_x                       int64
team_x                        object
position_x_x                  object
status                        object
height                       float64
weight                       float64
birth_date                    object
age_at_injury                float64
years_exp                    float64
injury_category               object
report_primary_injury_x       object
report_secondary_injury       object
practice_primary_injury       object
practice_secondary_injury     object
report_status_x               object
practice_status_x             object
days_since_last_injury       float64
previous_injuries_count        int64
dtype: object

In [39]:
# Assuming df is your original DataFrame

# Count the occurrences of 'Out' for each 'id'
out_counts = df[df['report_status_x'] == 'Out'].groupby('gsis_id').size().reset_index(name='Out_Count')

# Create a new DataFrame with unique 'id' values
unique_ids = pd.DataFrame({'gsis_id': df['gsis_id'].unique()})

# Merge the DataFrames on 'id'
result_df = pd.merge(unique_ids, out_counts, on='gsis_id', how='left').fillna(0)

# Display the result
result_df.head(20)

       gsis_id  Out_Count
0   00-0032889       17.0
1   00-0035676        0.0
2   00-0032255        0.0
3   00-0035190        0.0
4   00-0036265        0.0
5   00-0036192        0.0
6   00-0036114        0.0
7   00-0027942      136.0
8   00-0036752       19.0
9   00-0036285       51.0
10  00-0036551       20.0
11  00-0028946        0.0
12  00-0036171        0.0
13  00-0031388      102.0
14  00-0033293        0.0
15  00-0036465       34.0
16  00-0036899       38.0
17  00-0023459        0.0
18  00-0037812        0.0
19  00-0033064       19.0

In [40]:
# check that this is the same length as the number of unique players
result_df.shape

(1389, 2)

### Checking 'Out' Count accuracy

In [41]:
# check that the count was correct
ajbrown = df[df['gsis_id'] == '00-0035676']
ajbrown.tail()

,Unnamed: 0,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
2189,2189,a.j. brown,00-0035676,2020.0,NaN,2022,PHI,WR,ACT,73.0,...,3.0,Other,NaN,NaN,Not injury related - resting player,NaN,NaN,Limited Participation in Practice,0.0,359
2190,2190,a.j. brown,00-0035676,2020.0,NaN,2022,PHI,WR,ACT,73.0,...,3.0,Other,NaN,NaN,Not injury related - resting player,NaN,NaN,Limited Participation in Practice,0.0,359
2191,2191,a.j. brown,00-0035676,NaN,2021.0,2022,PHI,WR,ACT,73.0,...,3.0,Other,NaN,NaN,Not injury related - resting player,NaN,NaN,Limited Participation in Practice,0.0,359
2192,2192,a.j. brown,00-0035676,NaN,2021.0,2022,PHI,WR,ACT,73.0,...,3.0,Other,NaN,NaN,Not injury related - resting player,NaN,NaN,Limited Participation in Practice,0.0,359
2193,2193,a.j. brown,00-0035676,NaN,2021.0,2022,PHI,WR,ACT,73.0,...,3.0,Other,NaN,NaN,Not injury related - resting player,NaN,NaN,Limited Participation in Practice,0.0,359

In [42]:
ajgreen = df[df['gsis_id'] == '00-0027942']
ajgreen['team_x'].value_counts(normalize=True)

ARI    1.0
Name: team_x, dtype: float64

In [43]:
ajgreen.head()

,Unnamed: 0,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
2546,2546,a.j. green,00-0027942,NaN,2021.0,2022,ARI,WR,ACT,76.0,...,11.0,Other,NaN,NaN,Not injury related - resting player,NaN,NaN,Did Not Participate In Practice,12.0,34
2547,2547,a.j. green,00-0027942,NaN,2021.0,2022,ARI,WR,ACT,76.0,...,11.0,Other,NaN,NaN,Not injury related - resting player,NaN,NaN,Did Not Participate In Practice,12.0,34
2548,2548,a.j. green,00-0027942,NaN,2021.0,2022,ARI,WR,ACT,76.0,...,11.0,Other,NaN,NaN,Not injury related - resting player,NaN,NaN,Did Not Participate In Practice,12.0,34
2549,2549,a.j. green,00-0027942,NaN,2021.0,2022,ARI,WR,ACT,76.0,...,11.0,Other,NaN,NaN,Not injury related - resting player,NaN,NaN,Did Not Participate In Practice,12.0,34
2550,2550,a.j. green,00-0027942,NaN,2021.0,2022,ARI,WR,ACT,76.0,...,11.0,Other,NaN,NaN,Not injury related - resting player,NaN,NaN,Did Not Participate In Practice,0.0,35

# Double Checking Data Cleaning

In [44]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

#Import data
injuries_df = pd.read_csv('../1_DataCollection/src/injuries.csv')
rosters_df = pd.read_csv('../1_DataCollection/src/team_rosters.csv')

In [45]:
## CHECK DF SIZES
print(injuries_df.shape)
print(rosters_df.shape)

(5682, 16)
(46163, 37)

In [46]:
injuries_df['report_primary_injury'].unique()

array([nan, 'Ankle', 'Hamstring', 'Toe', 'Illness', 'Calf', 'Neck',
       'Quadricep', 'Knee', 'Not injury related - resting player', 'Foot',
       'Thigh', 'Elbow', 'Shoulder', 'Back', 'Groin', 'Pectoral', 'Heel',
       'Biceps', 'Hip', 'Collarbone', 'Hernia', 'Triceps', 'Thumb', 'Rib',
       'Concussion', 'Shin', 'right Thumb', 'Wrist', 'Finger',
       'Not injury related - personal matter', 'left Ankle', 'Ribs',
       'Appendicitis', 'Abdomen', 'Achilles', 'Appendix', 'Glute', 'Hand',
       'right Hip', 'right Groin', 'Chest', 'right Quadricep',
       'right Ankle', 'ankle, knee, elbow', 'right Hamstring',
       'right Finger', 'Oblique', 'right Shoulder',
       'Not injury related - did not travel', 'Eye', 'right Elbow',
       'Oblique ', 'appendix', 'right Calf', 'Forearm', 'left Shoulder',
       'Jaw', 'Fibula', 'kidney', 'right Knee', 'Throat',
       'Toe, Pec, Knee, Hip', 'Not injury related - other', 'Pelvis',
       'toe, pec, knee, hip'], dtype=object)

In [47]:
injuries_df[injuries_df['full_name'] == 'Tom Brady']

,season,game_type,team,week,gsis_id,position,full_name,first_name,last_name,report_primary_injury,report_secondary_injury,report_status,practice_primary_injury,practice_secondary_injury,practice_status,date_modified
393,2022,REG,TB,2,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,Not injury related - resting player,NaN,Full Participation in Practice,2022-09-16 19:29:23+00:00
670,2022,REG,TB,3,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,right Finger,NaN,Full Participation in Practice,2022-09-23 19:35:12+00:00
989,2022,REG,TB,4,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,right Finger,NaN,Full Participation in Practice,2022-09-30 19:58:52+00:00
1337,2022,REG,TB,5,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,right Shoulder,right Finger,Full Participation in Practice,2022-10-07 18:10:16+00:00
2279,2022,REG,TB,8,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,Not injury related - resting player,NaN,Limited Participation in Practice,2022-10-26 19:30:34+00:00
2556,2022,REG,TB,9,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,Not injury related - resting player,NaN,Full Participation in Practice,2022-11-04 19:24:33+00:00
2862,2022,REG,TB,10,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,Not injury related - resting player,NaN,Full Participation in Practice,2022-11-11 17:07:55+00:00
3473,2022,REG,TB,12,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,Not injury related - resting player,NaN,Full Participation in Practice,2022-11-25 20:11:01+00:00
3802,2022,REG,TB,13,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,Not injury related - resting player,NaN,Full Participation in Practice,2022-12-03 19:27:43+00:00
4765,2022,REG,TB,16,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,Not injury related - resting player,NaN,Full Participation in Practice,2022-12-23 19:12:16+00:00
5087,2022,REG,TB,17,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,Not injury related - resting player,NaN,Full Participation in Practice,2022-12-30 18:31:34+00:00
5417,2022,REG,TB,18,00-0019596,QB,Tom Brady,Tom,Brady,NaN,NaN,NaN,Not injury related - resting player,NaN,Full Participation in Practice,2023-01-06 18:36:22+00:00

In [48]:
rosters_df[rosters_df['player_name'] == 'Tom Brady']

,season,team,position,depth_chart_position,jersey_number,status,player_name,first_name,last_name,birth_date,...,status_description_abbr,football_name,esb_id,gsis_it_id,smart_id,entry_year,rookie_year,draft_club,draft_number,age
0,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.279
1,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.432
2,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.355
3,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.413
4,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.202
5,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.164
6,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.221
7,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.125
8,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.183
9,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.454
10,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.339
11,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.317
12,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.144
13,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.106
14,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.394
15,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.232
16,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.374
17,2022,TB,QB,QB,12.0,ACT,Tom Brady,Tom,Brady,1977-08-03,...,A01,Tom,BRA371156,25511,32004252-4137-1156-7ed0-8b9e44948f13,2000,2000.0,NE,199.0,45.259

In [49]:
# Merging the datasets on the common identifier gsis_id may not be the best approach
merged_df = pd.merge(injuries_df, rosters_df, left_on=['full_name'], right_on=['player_name'], how='left')

print(merged_df.shape)

# Convert date columns to datetime
merged_df['date_modified'] = pd.to_datetime(merged_df['date_modified'])
merged_df['birth_date'] = pd.to_datetime(merged_df['birth_date'])

print(merged_df.shape)

# Calculate age at the time of injury
merged_df['age_at_injury'] = merged_df['date_modified'].dt.year - merged_df['birth_date'].dt.year

print(merged_df.shape)

# Categorize injury types
# This is a placeholder 
merged_df['injury_category'] = merged_df['report_primary_injury'].apply(lambda x: 'Upper Body' if x in ['Shoulder', 'Arm'] else 'Lower Body' if x in ['Leg', 'Knee'] else 'Other')

print(merged_df.shape)

# Calculate time since last injury
merged_df = merged_df.sort_values(by=['full_name', 'date_modified'])
merged_df['days_since_last_injury'] = merged_df.groupby('full_name')['date_modified'].diff().dt.days.fillna(0)

print(merged_df.shape)

# Count of previous injuries
merged_df['previous_injuries_count'] = merged_df.groupby('full_name').cumcount()

print(merged_df.shape)

# Displaying the first few rows of the merged and modified dataset
#merged_df.head()

(102531, 53)
(102531, 53)
(102531, 54)
(102531, 55)
(102531, 56)
(102531, 57)

In [50]:
merged_df = merged_df[['full_name', 'gsis_id', 'season_x', 'team_x', 'position_x', 'status', 'height', 'weight', 'birth_date', 'age_at_injury', 'years_exp', 'injury_category', 'report_primary_injury', 'report_secondary_injury','practice_primary_injury', 'practice_secondary_injury', 'report_status', 'practice_status', 'days_since_last_injury', 'previous_injuries_count']]

merged_df.head()

,full_name,gsis_id,season_x,team_x,position_x,status,height,weight,birth_date,age_at_injury,years_exp,injury_category,report_primary_injury,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status,practice_status,days_since_last_injury,previous_injuries_count
55246,A'Shawn Robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,0
55247,A'Shawn Robinson,00-0032889,2022,LA,DT,ACT,76.0,330.0,1995-03-21,27.0,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,1
55248,A'Shawn Robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,2
55249,A'Shawn Robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,3
55250,A'Shawn Robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,4

In [51]:

past_injuries = pd.read_csv('../data/cleaned_scraped_data.csv', index_col=0)

past_injuries = past_injuries[~past_injuries['Injury'].isna()]

past_injuries.rename(columns={
    'Player': 'full_name',  
    'Position': 'position_x',  
    'Injury': 'report_primary_injury',
    'Game Status': 'practice_status',
    'Game Type': 'report_status',
}, inplace=True)
past_injuries['season'] = pd.to_numeric(past_injuries['season'], errors='coerce')
past_injuries.head()

,full_name,position_x,report_primary_injury,practice_status,report_status,game_type,season
1,Brandin Cooks,WR,Quadricep,Limited Participation in Practice,Questionable,REG,2020
3,Cullen Gillaspia,RB,Hamstring,Limited Participation in Practice,Questionable,REG,2020
4,Jonathan Greenard,LB,Ankle,Limited Participation in Practice,Questionable,REG,2020
15,Derek Barnett,DE,Hamstring,Limited Participation in Practice,Out,REG,2020
17,Javon Hargrave,DT,"Pectoral, Hamstring",Did Not Participate In Practice,Out,REG,2020

In [52]:
past_injuries['season_21'] = [2021 if x == 2021 else np.nan for x in past_injuries['season']]
past_injuries['season'] = [x if x != 2021 else np.nan for x in past_injuries['season']]
past_injuries['season_20'] = past_injuries['season']
past_injuries = past_injuries.drop(columns=['season'])

past_injuries.head()

,full_name,position_x,report_primary_injury,practice_status,report_status,game_type,season_21,season_20
1,Brandin Cooks,WR,Quadricep,Limited Participation in Practice,Questionable,REG,NaN,2020.0
3,Cullen Gillaspia,RB,Hamstring,Limited Participation in Practice,Questionable,REG,NaN,2020.0
4,Jonathan Greenard,LB,Ankle,Limited Participation in Practice,Questionable,REG,NaN,2020.0
15,Derek Barnett,DE,Hamstring,Limited Participation in Practice,Out,REG,NaN,2020.0
17,Javon Hargrave,DT,"Pectoral, Hamstring",Did Not Participate In Practice,Out,REG,NaN,2020.0

In [53]:
past_injuries.dtypes

full_name                 object
position_x                object
report_primary_injury     object
practice_status           object
report_status             object
game_type                 object
season_21                float64
season_20                float64
dtype: object

In [54]:
#Format names for merging
past_injuries['full_name'] = past_injuries['full_name'].str.strip().str.lower()
merged_df['full_name'] = merged_df['full_name'].str.strip().str.lower()

#Merge on name and season
final_merged_df = pd.merge(merged_df, past_injuries, left_on=['full_name',], right_on=['full_name'], how='left')

final_merged_df.head()

,full_name,gsis_id,season_x,team_x,position_x_x,status,height,weight,birth_date,age_at_injury,...,practice_status_x,days_since_last_injury,previous_injuries_count,position_x_y,report_primary_injury_y,practice_status_y,report_status_y,game_type,season_21,season_20
0,a'shawn robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,...,Did Not Participate In Practice,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a'shawn robinson,00-0032889,2022,LA,DT,ACT,76.0,330.0,1995-03-21,27.0,...,Did Not Participate In Practice,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a'shawn robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,...,Did Not Participate In Practice,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a'shawn robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,...,Did Not Participate In Practice,0.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,a'shawn robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,...,Did Not Participate In Practice,0.0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
final_merged_df.shape

(308923, 27)

In [56]:
def clean_data(final_merged_df):
    # Drop column: 'game_type'
    final_merged_df = final_merged_df.drop(columns=['game_type'])
    # Drop column: 'report_status_y'
    final_merged_df = final_merged_df.drop(columns=['report_status_y'])
    # Drop column: 'practice_status_y'
    final_merged_df = final_merged_df.drop(columns=['practice_status_y'])
    # Drop column: 'report_primary_injury_y'
    final_merged_df = final_merged_df.drop(columns=['report_primary_injury_y'])
    # Drop column: 'position_x_y'
    final_merged_df = final_merged_df.drop(columns=['position_x_y'])
    return final_merged_df

merged_clean = clean_data(final_merged_df.copy())
merged_clean.head()

,full_name,gsis_id,season_x,team_x,position_x_x,status,height,weight,birth_date,age_at_injury,...,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count,season_21,season_20
0,a'shawn robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,...,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,0,NaN,NaN
1,a'shawn robinson,00-0032889,2022,LA,DT,ACT,76.0,330.0,1995-03-21,27.0,...,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,1,NaN,NaN
2,a'shawn robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,...,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,2,NaN,NaN
3,a'shawn robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,...,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,3,NaN,NaN
4,a'shawn robinson,00-0032889,2022,LA,DT,RES,76.0,330.0,1995-03-21,27.0,...,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,4,NaN,NaN

In [57]:
merged_clean.columns

Index(['full_name', 'gsis_id', 'season_x', 'team_x', 'position_x_x', 'status',
       'height', 'weight', 'birth_date', 'age_at_injury', 'years_exp',
       'injury_category', 'report_primary_injury_x', 'report_secondary_injury',
       'practice_primary_injury', 'practice_secondary_injury',
       'report_status_x', 'practice_status_x', 'days_since_last_injury',
       'previous_injuries_count', 'season_21', 'season_20'],
      dtype='object')

In [58]:
final_merged_df = final_merged_df[['full_name', 'gsis_id', 'season_20', 'season_21', 'season_x', 'team_x', 'position_x_x',
       'status', 'height', 'weight', 'birth_date', 'age_at_injury',
       'years_exp', 'injury_category', 'report_primary_injury_x',
       'report_secondary_injury', 'practice_primary_injury',
       'practice_secondary_injury', 'report_status_x', 'practice_status_x',
      'days_since_last_injury', 'previous_injuries_count' ]]

In [59]:
final_merged_df.shape

(308923, 22)

In [60]:
#final_merged_df.to_csv('./cleaned_data/clean_merged_data.csv') 
final_merged_df.head()

,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,0
1,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,ACT,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,1
2,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,2
3,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,3
4,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,4

In [61]:
# 1. Creating a Column for Each Injury Type
# This creates a pivot table with players as rows and injury types as columns #REF: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot_table.html
injury_counts = final_merged_df.pivot_table(index='full_name', columns='report_primary_injury_x', aggfunc='size', fill_value=0)
print(injury_counts.shape)
#injury_counts.to_csv('./cleaned_data/injury_counts.csv')
injury_counts.head()

(1031, 65)

report_primary_injury_x,Abdomen,Achilles,Ankle,Appendicitis,Appendix,Back,Biceps,Calf,Chest,Collarbone,...,right Elbow,right Finger,right Groin,right Hamstring,right Hip,right Knee,right Quadricep,right Shoulder,right Thumb,"toe, pec, knee, hip"
full_name,,,,,,,,,,,,,,,,,,,,,
a'shawn robinson,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
a.j. cann,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
a.j. epenesa,0,0,38,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
a.j. green,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
a.j. parker,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [62]:
final_merged_df.head()

,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,0
1,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,ACT,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,1
2,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,2
3,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,3
4,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,330.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,4

# DF for modeling, No illness, Out counts, OHE for injury types

In [63]:
df = pd.read_csv('../2_DataCleaning/cleaned_data/clean_merged_data.csv')

In [64]:
print(df.shape)
df.head()

(308923, 23)

,Unnamed: 0,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,0,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,0
1,1,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,ACT,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,1
2,2,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,2
3,3,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,3
4,4,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Other,Illness,NaN,Illness,NaN,Questionable,Did Not Participate In Practice,0.0,4

In [65]:
df.dtypes

Unnamed: 0                     int64
full_name                     object
gsis_id                       object
season_20                    float64
season_21                    float64
season_x                       int64
team_x                        object
position_x_x                  object
status                        object
height                       float64
weight                       float64
birth_date                    object
age_at_injury                float64
years_exp                    float64
injury_category               object
report_primary_injury_x       object
report_secondary_injury       object
practice_primary_injury       object
practice_secondary_injury     object
report_status_x               object
practice_status_x             object
days_since_last_injury       float64
previous_injuries_count        int64
dtype: object

## Drop illnesses

In [66]:
## Drop rows with illness as primary injury
print(df[df['report_primary_injury_x'] != 'Illness'].shape)
df = df[df['report_primary_injury_x'] != 'Illness']

(300726, 23)

In [67]:
df[df['report_status_x'] == 'Out'].head()

,Unnamed: 0,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
17,17,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,6.0,17
18,18,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,ACT,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,18
19,19,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,19
20,20,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,20
21,21,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,21

## Checking which injuries were in each year

In [68]:
print(df['season_20'].unique())
print(df['season_21'].unique())
print(df['season_x'].unique())

[  nan 2020.]
[  nan 2021.]
[2022]

## DF for Out counts

In [69]:
# Assuming df is your original DataFrame

# Count the occurrences of 'Out' for each 'id'
out_counts = df[df['report_status_x'] == 'Out'].groupby('gsis_id').size().reset_index(name='Out_Count')

# Create a new DataFrame with unique 'id' values
unique_ids = pd.DataFrame({'gsis_id': df['gsis_id'].unique()})

# Merge the DataFrames on 'id'
out_df = pd.merge(unique_ids, out_counts, on='gsis_id', how='left').fillna(0)

# Display the result
out_df.head(20)

       gsis_id  Out_Count
0   00-0032889       17.0
1   00-0035676        0.0
2   00-0032255        0.0
3   00-0035190        0.0
4   00-0036265        0.0
5   00-0036192        0.0
6   00-0036114        0.0
7   00-0027942      136.0
8   00-0036752       19.0
9   00-0036285       51.0
10  00-0036551       20.0
11  00-0028946        0.0
12  00-0036171        0.0
13  00-0031388      102.0
14  00-0033293        0.0
15  00-0036465       34.0
16  00-0036899       38.0
17  00-0023459        0.0
18  00-0037812        0.0
19  00-0033064       19.0

In [70]:
# check that this is the same length as the number of unique players
out_df.shape

(1389, 2)

In [71]:
# this says the highest number of Out counts is 1665, which doesnt make sense
out_df['Out_Count'].max()

1665.0

## 2020 Out counts

In [72]:
# Filter for only '2020' in 'season_20'
df_2020 = df[df['season_20'] == 2020]
df_2020.shape

(122567, 23)

In [73]:
# Count the occurrences of 'Out' for each 'id'
out_counts_20 = df_2020[df_2020['report_status_x'] == 'Out'].groupby('gsis_id').size().reset_index(name='Out_Count_2020')

# Create a new DataFrame with unique 'id' values
unique_ids_20 = pd.DataFrame({'gsis_id': df_2020['gsis_id'].unique()})

# Merge the DataFrames on 'id'
out_20_df = pd.merge(unique_ids_20, out_counts_20, on='gsis_id', how='left').fillna(0)

# Display the result
print(out_20_df.shape)
out_20_df.head()

(508, 2)

      gsis_id  Out_Count_2020
0  00-0035676             0.0
1  00-0032255             0.0
2  00-0033293             0.0
3  00-0033878           665.0
4  00-0033783           357.0

## 2021 Out counts

In [74]:
# Filter for only '2021' in 'season_21'
df_2021 = df[df['season_21'] == 2021]
df_2021.shape

(144354, 23)

In [75]:
# Count the occurrences of 'Out' for each 'id'
out_counts_21 = df_2021[df_2021['report_status_x'] == 'Out'].groupby('gsis_id').size().reset_index(name='Out_Count_2021')

# Create a new DataFrame with unique 'id' values
unique_ids_21 = pd.DataFrame({'gsis_id': df_2021['gsis_id'].unique()})

# Merge the DataFrames on 'id'
out_21_df = pd.merge(unique_ids_21, out_counts_21, on='gsis_id', how='left').fillna(0)

# Display the result
print(out_21_df.shape)
out_21_df.head()

(592, 2)

      gsis_id  Out_Count_2021
0  00-0035676             0.0
1  00-0036192             0.0
2  00-0036114             0.0
3  00-0027942           136.0
4  00-0036285            51.0

## 2022 Out counts

In [76]:
# Filter for not in '2021' in 'season_21'
df_2022 = df[df['season_21'] != 2021]
df_2022.shape

(156372, 23)

In [77]:
# Filter for not in '2020' in 'season_20'
df_2022 = df_2022[df_2022['season_20'] != 2020]
df_2022.shape

(33805, 23)

In [78]:
# Count the occurrences of 'Out' for each 'id'
out_counts_22 = df_2022[df_2022['report_status_x'] == 'Out'].groupby('gsis_id').size().reset_index(name='Out_Count_2022')

# Create a new DataFrame with unique 'id' values
unique_ids_22 = pd.DataFrame({'gsis_id': df_2022['gsis_id'].unique()})

# Merge the DataFrames on 'id'
out_22_df = pd.merge(unique_ids_22, out_counts_22, on='gsis_id', how='left').fillna(0)

# Display the result
print(out_22_df.shape)
out_22_df.head()

(596, 2)

      gsis_id  Out_Count_2022
0  00-0032889            17.0
1  00-0035190             0.0
2  00-0036265             0.0
3  00-0036752            19.0
4  00-0036551            20.0

## Binary target for Out in 2022

In [79]:

# Create a new binary column with 1 if the player missed time in 2022, 0 if they did not
out_22_df['Injured_in_2022'] = out_22_df['Out_Count_2022'].apply(lambda x: 0 if x == 0 else 1)
out_22_df.head()

      gsis_id  Out_Count_2022  Injured_in_2022
0  00-0032889            17.0                1
1  00-0035190             0.0                0
2  00-0036265             0.0                0
3  00-0036752            19.0                1
4  00-0036551            20.0                1

## Filtering to only include one row per player

In [80]:
print(df.shape)
df.head()

(300726, 23)

,Unnamed: 0,full_name,gsis_id,season_20,season_21,season_x,team_x,position_x_x,status,height,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
17,17,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,6.0,17
18,18,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,ACT,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,18
19,19,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,19
20,20,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,20
21,21,a'shawn robinson,00-0032889,NaN,NaN,2022,LA,DT,RES,76.0,...,6.0,Lower Body,Knee,NaN,Knee,NaN,Out,Did Not Participate In Practice,0.0,21

In [81]:
# Drop unnamed column
df = df.drop(columns = ['Unnamed: 0'])

# take only last row for each id
df_by_id = df.groupby('gsis_id', as_index=False).last()

#sort by id
df_by_id = df_by_id.sort_values('gsis_id')

df_by_id.head()

,gsis_id,full_name,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,00-0019596,tom brady,NaN,NaN,2022,TB,QB,ACT,76.0,225.0,...,22.0,Other,None,None,Not injury related - resting player,right Finger,None,Full Participation in Practice,0.0,215
1,00-0022531,jason peters,2020.0,2021.0,2022,DAL,T,DEV,76.0,328.0,...,18.0,Other,Hip,None,Hip,None,Out,Did Not Participate In Practice,0.0,75
2,00-0023252,robbie gould,NaN,NaN,2022,SF,K,ACT,72.0,190.0,...,17.0,Other,None,None,left Knee,None,None,Full Participation in Practice,0.0,19
3,00-0023459,aaron rodgers,NaN,NaN,2022,GB,QB,ACT,74.0,225.0,...,17.0,Other,None,None,right Thumb,Knee,None,Full Participation in Practice,0.0,203
4,00-0023853,matt prater,2020.0,NaN,2022,ARI,K,INA,70.0,201.0,...,16.0,Other,right Hip,Illness,right Hip,Illness,Questionable,Full Participation in Practice,0.0,135

In [82]:
df_by_id.shape

(1389, 22)

In [83]:
df_by_id.dtypes

gsis_id                       object
full_name                     object
season_20                    float64
season_21                    float64
season_x                       int64
team_x                        object
position_x_x                  object
status                        object
height                       float64
weight                       float64
birth_date                    object
age_at_injury                float64
years_exp                    float64
injury_category               object
report_primary_injury_x       object
report_secondary_injury       object
practice_primary_injury       object
practice_secondary_injury     object
report_status_x               object
practice_status_x             object
days_since_last_injury       float64
previous_injuries_count        int64
dtype: object

## Mapping Out counts to df_by_id

In [84]:
print(out_df.shape)
out_df.head()

(1389, 2)

      gsis_id  Out_Count
0  00-0032889       17.0
1  00-0035676        0.0
2  00-0032255        0.0
3  00-0035190        0.0
4  00-0036265        0.0

In [85]:
print(df_by_id.shape)
df_by_id.head()

(1389, 22)

,gsis_id,full_name,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,years_exp,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count
0,00-0019596,tom brady,NaN,NaN,2022,TB,QB,ACT,76.0,225.0,...,22.0,Other,None,None,Not injury related - resting player,right Finger,None,Full Participation in Practice,0.0,215
1,00-0022531,jason peters,2020.0,2021.0,2022,DAL,T,DEV,76.0,328.0,...,18.0,Other,Hip,None,Hip,None,Out,Did Not Participate In Practice,0.0,75
2,00-0023252,robbie gould,NaN,NaN,2022,SF,K,ACT,72.0,190.0,...,17.0,Other,None,None,left Knee,None,None,Full Participation in Practice,0.0,19
3,00-0023459,aaron rodgers,NaN,NaN,2022,GB,QB,ACT,74.0,225.0,...,17.0,Other,None,None,right Thumb,Knee,None,Full Participation in Practice,0.0,203
4,00-0023853,matt prater,2020.0,NaN,2022,ARI,K,INA,70.0,201.0,...,16.0,Other,right Hip,Illness,right Hip,Illness,Questionable,Full Participation in Practice,0.0,135

In [86]:
# join
merged_df = df_by_id.merge(out_df, on='gsis_id', how='left')

# Rename the column
merged_df = merged_df.rename(columns={'Out_Count': 'Out_Count'})

# Fill na
merged_df['Out_Count'] = merged_df['Out_Count'].fillna(0)

print(merged_df.shape)
merged_df.head()

(1389, 23)

,gsis_id,full_name,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,injury_category,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count,Out_Count
0,00-0019596,tom brady,NaN,NaN,2022,TB,QB,ACT,76.0,225.0,...,Other,None,None,Not injury related - resting player,right Finger,None,Full Participation in Practice,0.0,215,0.0
1,00-0022531,jason peters,2020.0,2021.0,2022,DAL,T,DEV,76.0,328.0,...,Other,Hip,None,Hip,None,Out,Did Not Participate In Practice,0.0,75,133.0
2,00-0023252,robbie gould,NaN,NaN,2022,SF,K,ACT,72.0,190.0,...,Other,None,None,left Knee,None,None,Full Participation in Practice,0.0,19,0.0
3,00-0023459,aaron rodgers,NaN,NaN,2022,GB,QB,ACT,74.0,225.0,...,Other,None,None,right Thumb,Knee,None,Full Participation in Practice,0.0,203,0.0
4,00-0023853,matt prater,2020.0,NaN,2022,ARI,K,INA,70.0,201.0,...,Other,right Hip,Illness,right Hip,Illness,Questionable,Full Participation in Practice,0.0,135,34.0

## Repeating Merge for each year

In [87]:
# join 2020 injuries
merged_df = merged_df.merge(out_20_df, on='gsis_id', how='left')

# Rename the column
merged_df = merged_df.rename(columns={'Out_Count_2020': 'Out_Count_2020'})

# Fill na
merged_df['Out_Count_2020'] = merged_df['Out_Count_2020'].fillna(0)

print(merged_df.shape)
merged_df.head()

(1389, 24)

,gsis_id,full_name,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,report_primary_injury_x,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count,Out_Count,Out_Count_2020
0,00-0019596,tom brady,NaN,NaN,2022,TB,QB,ACT,76.0,225.0,...,None,None,Not injury related - resting player,right Finger,None,Full Participation in Practice,0.0,215,0.0,0.0
1,00-0022531,jason peters,2020.0,2021.0,2022,DAL,T,DEV,76.0,328.0,...,Hip,None,Hip,None,Out,Did Not Participate In Practice,0.0,75,133.0,57.0
2,00-0023252,robbie gould,NaN,NaN,2022,SF,K,ACT,72.0,190.0,...,None,None,left Knee,None,None,Full Participation in Practice,0.0,19,0.0,0.0
3,00-0023459,aaron rodgers,NaN,NaN,2022,GB,QB,ACT,74.0,225.0,...,None,None,right Thumb,Knee,None,Full Participation in Practice,0.0,203,0.0,0.0
4,00-0023853,matt prater,2020.0,NaN,2022,ARI,K,INA,70.0,201.0,...,right Hip,Illness,right Hip,Illness,Questionable,Full Participation in Practice,0.0,135,34.0,34.0

In [88]:
# join 2021 injuries
merged_df = merged_df.merge(out_21_df, on='gsis_id', how='left')

# Rename the column
merged_df = merged_df.rename(columns={'Out_Count_2021': 'Out_Count_2021'})

# Fill na
merged_df['Out_Count_2021'] = merged_df['Out_Count_2021'].fillna(0)

print(merged_df.shape)
merged_df.head()

(1389, 25)

,gsis_id,full_name,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,report_secondary_injury,practice_primary_injury,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count,Out_Count,Out_Count_2020,Out_Count_2021
0,00-0019596,tom brady,NaN,NaN,2022,TB,QB,ACT,76.0,225.0,...,None,Not injury related - resting player,right Finger,None,Full Participation in Practice,0.0,215,0.0,0.0,0.0
1,00-0022531,jason peters,2020.0,2021.0,2022,DAL,T,DEV,76.0,328.0,...,None,Hip,None,Out,Did Not Participate In Practice,0.0,75,133.0,57.0,76.0
2,00-0023252,robbie gould,NaN,NaN,2022,SF,K,ACT,72.0,190.0,...,None,left Knee,None,None,Full Participation in Practice,0.0,19,0.0,0.0,0.0
3,00-0023459,aaron rodgers,NaN,NaN,2022,GB,QB,ACT,74.0,225.0,...,None,right Thumb,Knee,None,Full Participation in Practice,0.0,203,0.0,0.0,0.0
4,00-0023853,matt prater,2020.0,NaN,2022,ARI,K,INA,70.0,201.0,...,Illness,right Hip,Illness,Questionable,Full Participation in Practice,0.0,135,34.0,34.0,0.0

In [89]:
# join 2022 injuries
merged_df = merged_df.merge(out_22_df, on='gsis_id', how='left')

# Rename the column
merged_df = merged_df.rename(columns={'Out_Count_2022': 'Out_Count_2022', 'Injured_in_2022': 'Injured_in_2022'})

# Fill na
merged_df['Out_Count_2022'] = merged_df['Out_Count_2022'].fillna(0)
merged_df['Injured_in_2022'] = merged_df['Injured_in_2022'].fillna(0)

print(merged_df.shape)
merged_df.head()

(1389, 27)

,gsis_id,full_name,season_20,season_21,season_x,team_x,position_x_x,status,height,weight,...,practice_secondary_injury,report_status_x,practice_status_x,days_since_last_injury,previous_injuries_count,Out_Count,Out_Count_2020,Out_Count_2021,Out_Count_2022,Injured_in_2022
0,00-0019596,tom brady,NaN,NaN,2022,TB,QB,ACT,76.0,225.0,...,right Finger,None,Full Participation in Practice,0.0,215,0.0,0.0,0.0,0.0,0.0
1,00-0022531,jason peters,2020.0,2021.0,2022,DAL,T,DEV,76.0,328.0,...,None,Out,Did Not Participate In Practice,0.0,75,133.0,57.0,76.0,0.0,0.0
2,00-0023252,robbie gould,NaN,NaN,2022,SF,K,ACT,72.0,190.0,...,None,None,Full Participation in Practice,0.0,19,0.0,0.0,0.0,0.0,0.0
3,00-0023459,aaron rodgers,NaN,NaN,2022,GB,QB,ACT,74.0,225.0,...,Knee,None,Full Participation in Practice,0.0,203,0.0,0.0,0.0,0.0,0.0
4,00-0023853,matt prater,2020.0,NaN,2022,ARI,K,INA,70.0,201.0,...,Illness,Questionable,Full Participation in Practice,0.0,135,34.0,34.0,0.0,0.0,0.0

## One Hot Encode Injury types

In [90]:
merged_df.dtypes

gsis_id                       object
full_name                     object
season_20                    float64
season_21                    float64
season_x                       int64
team_x                        object
position_x_x                  object
status                        object
height                       float64
weight                       float64
birth_date                    object
age_at_injury                float64
years_exp                    float64
injury_category               object
report_primary_injury_x       object
report_secondary_injury       object
practice_primary_injury       object
practice_secondary_injury     object
report_status_x               object
practice_status_x             object
days_since_last_injury       float64
previous_injuries_count        int64
Out_Count                    float64
Out_Count_2020               float64
Out_Count_2021               float64
Out_Count_2022               float64
Injured_in_2022              float64
dtype: object

In [91]:
modeling_df = merged_df.drop(columns = ['season_20', 'season_21', 'season_x', 'status', 'birth_date', 'report_secondary_injury', 
                                        'practice_primary_injury', 'practice_secondary_injury', 'report_status_x', 'practice_status_x', 
                                        'days_since_last_injury', 'previous_injuries_count'])

In [92]:
modeling_df.dtypes

gsis_id                     object
full_name                   object
team_x                      object
position_x_x                object
height                     float64
weight                     float64
age_at_injury              float64
years_exp                  float64
injury_category             object
report_primary_injury_x     object
Out_Count                  float64
Out_Count_2020             float64
Out_Count_2021             float64
Out_Count_2022             float64
Injured_in_2022            float64
dtype: object

In [93]:
modeling_df.to_csv('../5_ModelDevelopment/src/player_modeling_data.csv')

In [94]:
# Columns to be one-hot encoded
columns = ['position_x_x', 'injury_category', 'report_primary_injury_x']

# Perform one-hot encoding
modeling_df_encoded = pd.get_dummies(modeling_df, columns=columns)

# Display the result
modeling_df_encoded

,gsis_id,full_name,team_x,height,weight,age_at_injury,years_exp,Out_Count,Out_Count_2020,Out_Count_2021,...,report_primary_injury_x_right Calf,report_primary_injury_x_right Elbow,report_primary_injury_x_right Finger,report_primary_injury_x_right Groin,report_primary_injury_x_right Hamstring,report_primary_injury_x_right Hip,report_primary_injury_x_right Knee,report_primary_injury_x_right Shoulder,report_primary_injury_x_right Thumb,"report_primary_injury_x_toe, pec, knee, hip"
0,00-0019596,tom brady,TB,76.0,225.0,46.0,22.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,00-0022531,jason peters,DAL,76.0,328.0,41.0,18.0,133.0,57.0,76.0,...,0,0,0,0,0,0,0,0,0,0
2,00-0023252,robbie gould,SF,72.0,190.0,40.0,17.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,00-0023459,aaron rodgers,GB,74.0,225.0,40.0,17.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,00-0023853,matt prater,ARI,70.0,201.0,38.0,16.0,34.0,34.0,0.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,00-0038130,andrew booth,MIN,72.0,200.0,22.0,0.0,54.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1385,00-0038133,boye mafe,SEA,76.0,265.0,24.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1386,00-0038134,kenneth walker,SEA,69.0,210.0,23.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1387,00-0038135,jaquan brisker,CHI,73.0,202.0,24.0,0.0,34.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1388,00-0038142,david ojabo,BAL,76.0,250.0,22.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [95]:
modeling_df_encoded.to_csv('../5_ModelDevelopment/src/encoded_player_modeling_data.csv')

In [96]:
# Target is 'Injured_in_2022'
# Don't include 'Out_Count' or 'Out_Count_2022'

In [98]:
modeling_df_encoded.columns

Index(['gsis_id', 'full_name', 'team_x', 'height', 'weight', 'age_at_injury',
       'years_exp', 'Out_Count', 'Out_Count_2020', 'Out_Count_2021',
       'Out_Count_2022', 'Injured_in_2022', 'position_x_x_C',
       'position_x_x_CB', 'position_x_x_DE', 'position_x_x_DT',
       'position_x_x_FB', 'position_x_x_G', 'position_x_x_K',
       'position_x_x_LB', 'position_x_x_LS', 'position_x_x_P',
       'position_x_x_QB', 'position_x_x_RB', 'position_x_x_S',
       'position_x_x_T', 'position_x_x_TE', 'position_x_x_WR',
       'injury_category_Lower Body', 'injury_category_Other',
       'injury_category_Upper Body', 'report_primary_injury_x_Abdomen',
       'report_primary_injury_x_Achilles', 'report_primary_injury_x_Ankle',
       'report_primary_injury_x_Appendix', 'report_primary_injury_x_Back',
       'report_primary_injury_x_Biceps', 'report_primary_injury_x_Calf',
       'report_primary_injury_x_Chest', 'report_primary_injury_x_Collarbone',
       'report_primary_injury_x_Concussion', 'report_primary_injury_x_Elbow',
       'report_primary_injury_x_Eye', 'report_primary_injury_x_Fibula',
       'report_primary_injury_x_Finger', 'report_primary_injury_x_Foot',
       'report_primary_injury_x_Forearm', 'report_primary_injury_x_Groin',
       'report_primary_injury_x_Hamstring', 'report_primary_injury_x_Hand',
       'report_primary_injury_x_Heel', 'report_primary_injury_x_Hip',
       'report_primary_injury_x_Jaw', 'report_primary_injury_x_Knee',
       'report_primary_injury_x_Neck',
       'report_primary_injury_x_Not injury related - did not travel',
       'report_primary_injury_x_Not injury related - other',
       'report_primary_injury_x_Not injury related - personal matter',
       'report_primary_injury_x_Not injury related - resting player',
       'report_primary_injury_x_Oblique', 'report_primary_injury_x_Pectoral',
       'report_primary_injury_x_Pelvis', 'report_primary_injury_x_Quadricep',
       'report_primary_injury_x_Rib', 'report_primary_injury_x_Ribs',
       'report_primary_injury_x_Shin', 'report_primary_injury_x_Shoulder',
       'report_primary_injury_x_Thigh', 'report_primary_injury_x_Throat',
       'report_primary_injury_x_Thumb', 'report_primary_injury_x_Toe',
       'report_primary_injury_x_Wrist', 'report_primary_injury_x_kidney',
       'report_primary_injury_x_right Ankle',
       'report_primary_injury_x_right Calf',
       'report_primary_injury_x_right Elbow',
       'report_primary_injury_x_right Finger',
       'report_primary_injury_x_right Groin',
       'report_primary_injury_x_right Hamstring',
       'report_primary_injury_x_right Hip',
       'report_primary_injury_x_right Knee',
       'report_primary_injury_x_right Shoulder',
       'report_primary_injury_x_right Thumb',
       'report_primary_injury_x_toe, pec, knee, hip'],
      dtype='object')